### PR TITLE
R MCMC Lab

### PR DESCRIPTION
**Pull request by zamorarr**
First draft of MCMC from scratch lab in R based on python version. Seems to be working ok but haven't tested thoroughly. Will update over the next week. Anyone else should feel free to go in and fix anything I messed up.

Should probably merge Stevie's branch into master first before this one, since I inadvertently branched off of hers instead of master. :man_shrugging: 

- [x] add correlgrams
- [x] fix last plot not showing line samples

### CODE REVIEW

**Comment by Stevierene82** [comment]
Switched back to html document b/c this file has a ton of equations, and otherwise they don't render properly.

Removed all (I think) pieces of code relying on the zealot library

Created a separate .R file for test functions. This should allow users to just work inside the RMD doc w/o it yelling about incomplete code.

I only got through section 5. Overall looks pretty good to that point. Some changes to formatting/wording, some to make more consistent with python file. Fixed equation in 3.5 (still wrong in python version).

**Comment by Stevierene82** [comment]
added correlograms (sp?). Please double check me that I did that right.
fixed that final plot to show all the sample lines.
@zamorarr back to you!!

**Comment by zamorarr** [comment]
Everything looks good to me! Thanks for fixing my stuff. I only had some small changes:

- use `bquote()` to make nicer plot labels (theta symbols in particular)
- add a small blurb about MCMC and MH to refresh minds
- use `map()` instead of `apply()` + `gather()` to produce final plot

The final point is my suggestion because we have mentioned the `map()` functions in study group a few times but not `apply()` (tidyverse vs base R, etc ...)

Also at some point before Friday once this is nailed down we should create a solutions folder and put these files in there then go back and delete all the code that the students have to do themselves.

**Comment by Stevierene82** [comment]
Yeah...I should learn about that `map()` function one of these days.

I can work on setting up the student vs. solution files tomorrow night - it'll do me good to run through it all again.

**Comment by Stevierene82** [comment]
alright, updated with the student vs. solution files.

side note - it looks like we have slightly different setups. Whenever I knit the Rmd to html, it removes all of the figures that you had pushed up. I'm not sure if that is a remnant of using github_document or something else.

If you're good with everything, I think we're ready to push on up to master.

**Comment by zamorarr** [comment]
Yup I think we can merge this. The figures are generated by the github_document format, so that probably explains why you don't generate them anymore. Good team work @Stevierene82 !

**Pull request merged**
